FROM python:3.12

LABEL org.opencontainers.image.source https://github.com/miguelglopes/OML-aula

WORKDIR /app

COPY frontend/form.html index.html

EXPOSE 5003

CMD ["python", "-m", "http.server", "5003"]