name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codigo
        uses: actions/checkout@v4

      - name: install docker
        uses: docker/setup-buildx-action@v3

      - name: MLFLOW Tracking server + Service
        run: docker compose up --build

      - name: instalar dependencias do conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: OML
          environment-file: conda.yaml

      - name: Tests
        run: pytest