name: CI/CD

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codigo
        uses: actions/checkout@v4

      - name: install docker
        uses: docker/setup-buildx-action@v3

      - name: MLFLOW Tracking server + Service
        run: docker compose up -d --build

      - name: instalar dependencias do conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: OML
          environment-file: conda.yaml

      - name: Tests
        run: conda run --no-capture-output --name OML pytest